### ISSUE TITLE
Correct wrong library listed in locations.tsv

### ISSUE THREAD

**Issue by Laszlo-J** [sul-dlss/folio_migration#46]
Library should be fixed to:

line 222 = LAW
lines 223 = LAW
line 300 = SCIENCE

[https://github.com/sul-dlss/folio_migration/blob/main/mapping_files/locations.tsv#L300](url)

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/folio_migration/pull/new/fix-libraries
